version: 2
updates:
  - package-ecosystem: "docker-compose"
    directories:
      - "/docker/beszel"
      - "/docker/code-server"
      - "/docker/handbrake"
      - "/docker/homarr"
      - "/docker/home-assistant"
      - "/docker/it-tools"
      - "/docker/iventoy"
      - "/docker/kasm"
      - "/docker/metube"
      - "/docker/netbootxyz"
      - "/docker/netdata"
      - "/docker/networking-toolbox"
      - "/docker/ombi"
      - "/docker/open-webui"
      - "/docker/stirling-pdf"
      - "/docker/traefik"
      - "/docker/watchtower"
      - "/docker/webtop"
      - "/docker/zerobyte"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker-compose"
    directories:
      - "/docker/plex"
    schedule:
      interval: "daily"
    versioning-strategy: increase
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "weekly"
      day: "saturday"
